name: MSYS2
on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: false
          install: >-
            git
          pacboy: >-
            toolchain:p
            cmake:p
            json-c:p
            libusb:p
            hidapi:p

      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build -j $(nproc)
          cmake --install build --prefix out

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{github.workspace}}/out